# Copyright 2018, Steven W. Anderson
FROM jboss/wildfly:13.0.0.Final

USER jboss

COPY configuration/ /opt/jboss/wildfly/standalone/configuration/
COPY libs/ /opt/jboss/wildfly/standalone/deployments/
