apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  ports:
  - port: 61616
    name: jms
  selector:
    app: activemq
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  selector:
    matchLabels:
      app: activemq
  serviceName: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        stateful-target: "0"
      initContainers:
      - name: fix-perm
        image: busybox
        command: ["sh","-c","chmod 777 /tmp/data"]
        volumeMounts:
        - name: activemq-data-local-storage
          mountPath: /tmp/data
      containers:
      - name: activemq
        image: registry.lxdk8s:5000/research/devops/activemq:5.15.4
        ports:
        - containerPort: 61616
          name: jms
        - containerPort: 8161
          name: ui
        volumeMounts:
        - name: activemq-data-local-storage
          mountPath: /opt/activemq/data
      volumes:
      - name: activemq-data-local-storage
        hostPath:
          path: /var/local/storage/activemq/data
          type: DirectoryOrCreate
