---
- name: Create middle-server log storage
  file: path=/var/local/storage/middle-server/log state=directory mode="a+rwx"

- name: Create middle-server container
  docker_container:
    name: middle-server
    image: dregistry.swahome.net:7443/research/jast/middle-server:1.0
    restart_policy: always
    hostname: middle-server
    command: "/opt/jboss/wildfly/bin/standalone.sh --server-config=standalone-full.xml -Djboss.node.name=middle-server --debug 5000 -b 0.0.0.0 -bmanagement 0.0.0.0"
    links:
      - "back-server:back-server"
      - "activemq:activemq"
    ports:
     - "8081:8080"
     - "9991:9990"
    volumes:
     - /var/local/storage/middle-server/log:/opt/jboss/wildfly/standalone/log
